[project]
name = "reposgithub"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "flet>=0.28.3",
    "flet-cli>=0.28.3",
    "flet-web>=0.28.3",
    "requests>=2.32.4",
]
